services:
  bridge:
    build: ./bridge
    container_name: meross-bridge
    restart: unless-stopped
    env_file:
      - path: config/.env
        required: false
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - gui
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gui:
    build: ./gui
    container_name: meross-gui
    restart: unless-stopped
    env_file:
      - path: config/.env
        required: false
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
